# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\peng\Desktop\chia-tools\ui\HuobiPoolMineWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HuobiPoolMineWidget(object):
    def setupUi(self, HuobiPoolMineWidget):
        HuobiPoolMineWidget.setObjectName("HuobiPoolMineWidget")
        HuobiPoolMineWidget.resize(902, 526)
        self.verticalLayout = QtWidgets.QVBoxLayout(HuobiPoolMineWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(HuobiPoolMineWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.editMinerName = QtWidgets.QLineEdit(HuobiPoolMineWidget)
        self.editMinerName.setObjectName("editMinerName")
        self.horizontalLayout_3.addWidget(self.editMinerName)
        self.label = QtWidgets.QLabel(HuobiPoolMineWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.editApiKey = QtWidgets.QLineEdit(HuobiPoolMineWidget)
        self.editApiKey.setObjectName("editApiKey")
        self.horizontalLayout_3.addWidget(self.editApiKey)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.labelStatus = QtWidgets.QLabel(HuobiPoolMineWidget)
        self.labelStatus.setObjectName("labelStatus")
        self.horizontalLayout_3.addWidget(self.labelStatus)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.buttonStart = QtWidgets.QPushButton(HuobiPoolMineWidget)
        self.buttonStart.setObjectName("buttonStart")
        self.horizontalLayout_3.addWidget(self.buttonStart)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.textEditLog = QtWidgets.QTextEdit(HuobiPoolMineWidget)
        self.textEditLog.setObjectName("textEditLog")
        self.verticalLayout.addWidget(self.textEditLog)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBoxAutoStart = QtWidgets.QCheckBox(HuobiPoolMineWidget)
        self.checkBoxAutoStart.setObjectName("checkBoxAutoStart")
        self.horizontalLayout.addWidget(self.checkBoxAutoStart)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(HuobiPoolMineWidget)
        QtCore.QMetaObject.connectSlotsByName(HuobiPoolMineWidget)

    def retranslateUi(self, HuobiPoolMineWidget):
        _translate = QtCore.QCoreApplication.translate
        HuobiPoolMineWidget.setWindowTitle(_translate("HuobiPoolMineWidget", "Form"))
        self.label_2.setText(_translate("HuobiPoolMineWidget", "矿工名"))
        self.label.setText(_translate("HuobiPoolMineWidget", "Access-ID"))
        self.labelStatus.setText(_translate("HuobiPoolMineWidget", "    "))
        self.buttonStart.setText(_translate("HuobiPoolMineWidget", "开始挖矿"))
        self.checkBoxAutoStart.setText(_translate("HuobiPoolMineWidget", "开机自动启动并开始挖矿"))
