# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\peng\Desktop\chia-tools\ui\PlotCheckWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlotCheckWidget(object):
    def setupUi(self, PlotCheckWidget):
        PlotCheckWidget.setObjectName("PlotCheckWidget")
        PlotCheckWidget.resize(969, 628)
        self.verticalLayout = QtWidgets.QVBoxLayout(PlotCheckWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(PlotCheckWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinChallengeCount = QtWidgets.QSpinBox(PlotCheckWidget)
        self.spinChallengeCount.setMinimum(5)
        self.spinChallengeCount.setMaximum(200)
        self.spinChallengeCount.setProperty("value", 30)
        self.spinChallengeCount.setObjectName("spinChallengeCount")
        self.horizontalLayout.addWidget(self.spinChallengeCount)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.labelTotal = QtWidgets.QLabel(PlotCheckWidget)
        self.labelTotal.setText("")
        self.labelTotal.setObjectName("labelTotal")
        self.horizontalLayout.addWidget(self.labelTotal)
        self.progressCheck = QtWidgets.QProgressBar(PlotCheckWidget)
        self.progressCheck.setProperty("value", 0)
        self.progressCheck.setObjectName("progressCheck")
        self.horizontalLayout.addWidget(self.progressCheck)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.buttonStart = QtWidgets.QPushButton(PlotCheckWidget)
        self.buttonStart.setObjectName("buttonStart")
        self.horizontalLayout.addWidget(self.buttonStart)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.treePlots = QtWidgets.QTreeWidget(PlotCheckWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treePlots.sizePolicy().hasHeightForWidth())
        self.treePlots.setSizePolicy(sizePolicy)
        self.treePlots.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.treePlots.setFocusPolicy(QtCore.Qt.NoFocus)
        self.treePlots.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.treePlots.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.treePlots.setRootIsDecorated(False)
        self.treePlots.setItemsExpandable(False)
        self.treePlots.setObjectName("treePlots")
        self.verticalLayout.addWidget(self.treePlots)

        self.retranslateUi(PlotCheckWidget)
        QtCore.QMetaObject.connectSlotsByName(PlotCheckWidget)

    def retranslateUi(self, PlotCheckWidget):
        _translate = QtCore.QCoreApplication.translate
        PlotCheckWidget.setWindowTitle(_translate("PlotCheckWidget", "PlotCheckWidget"))
        self.label.setText(_translate("PlotCheckWidget", "挑战数量"))
        self.buttonStart.setText(_translate("PlotCheckWidget", "开始检查"))
        self.treePlots.setSortingEnabled(True)
        self.treePlots.headerItem().setText(0, _translate("PlotCheckWidget", "文件名"))
        self.treePlots.headerItem().setText(1, _translate("PlotCheckWidget", "K"))
        self.treePlots.headerItem().setText(2, _translate("PlotCheckWidget", "状态"))
        self.treePlots.headerItem().setText(3, _translate("PlotCheckWidget", "质量"))
        self.treePlots.headerItem().setText(4, _translate("PlotCheckWidget", "fpk"))
        self.treePlots.headerItem().setText(5, _translate("PlotCheckWidget", "ppk"))
        self.treePlots.headerItem().setText(6, _translate("PlotCheckWidget", "路径"))
