# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\peng\Desktop\chia-tools\ui\PlotCheckWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlotCheckWidget(object):
    def setupUi(self, PlotCheckWidget):
        PlotCheckWidget.setObjectName("PlotCheckWidget")
        PlotCheckWidget.resize(969, 628)
        self.verticalLayout = QtWidgets.QVBoxLayout(PlotCheckWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.buttonStart = QtWidgets.QPushButton(PlotCheckWidget)
        self.buttonStart.setObjectName("buttonStart")
        self.horizontalLayout.addWidget(self.buttonStart)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.treePlots = QtWidgets.QTreeWidget(PlotCheckWidget)
        self.treePlots.setRootIsDecorated(False)
        self.treePlots.setItemsExpandable(False)
        self.treePlots.setObjectName("treePlots")
        self.verticalLayout.addWidget(self.treePlots)

        self.retranslateUi(PlotCheckWidget)
        QtCore.QMetaObject.connectSlotsByName(PlotCheckWidget)

    def retranslateUi(self, PlotCheckWidget):
        _translate = QtCore.QCoreApplication.translate
        PlotCheckWidget.setWindowTitle(_translate("PlotCheckWidget", "PlotCheckWidget"))
        self.buttonStart.setText(_translate("PlotCheckWidget", "开始检查"))
        self.treePlots.setSortingEnabled(True)
        self.treePlots.headerItem().setText(0, _translate("PlotCheckWidget", "文件名"))
        self.treePlots.headerItem().setText(1, _translate("PlotCheckWidget", "K"))
        self.treePlots.headerItem().setText(2, _translate("PlotCheckWidget", "状态"))
        self.treePlots.headerItem().setText(3, _translate("PlotCheckWidget", "质量"))
        self.treePlots.headerItem().setText(4, _translate("PlotCheckWidget", "fpk"))
        self.treePlots.headerItem().setText(5, _translate("PlotCheckWidget", "ppk"))
