# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/peng/Documents/Projects/devteam.cn/ChiaTools/ui/TaskOutputDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TaskOutputDialog(object):
    def setupUi(self, TaskOutputDialog):
        TaskOutputDialog.setObjectName("TaskOutputDialog")
        TaskOutputDialog.resize(1107, 742)
        self.verticalLayout = QtWidgets.QVBoxLayout(TaskOutputDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.edit = QtWidgets.QTextEdit(TaskOutputDialog)
        self.edit.setObjectName("edit")
        self.verticalLayout.addWidget(self.edit)

        self.retranslateUi(TaskOutputDialog)
        QtCore.QMetaObject.connectSlotsByName(TaskOutputDialog)

    def retranslateUi(self, TaskOutputDialog):
        _translate = QtCore.QCoreApplication.translate
        TaskOutputDialog.setWindowTitle(_translate("TaskOutputDialog", "Dialog"))
